const siteMetadata = require("./src/utils/siteMetaData");

// You'll need to run something like 'npm build' then 'npm start' or 'npm run start' to create the acutal site, then use the URL generated by the sitemap for wherever you host the site

module.exports = {
    siteUrl: siteMetadata.siteUrl,
    generateRobotsTxt: true,
  }